/*
 * This file is generated by jOOQ.
 */
package org.gdg.withgo.data.database;


import javax.annotation.Generated;

import org.gdg.withgo.data.database.tables.Account;
import org.gdg.withgo.data.database.tables.Applicant;
import org.gdg.withgo.data.database.tables.Event;
import org.gdg.withgo.data.database.tables.Ticket;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = org.gdg.withgo.data.database.tables.Account.ACCOUNT;

    /**
     * The table <code>public.applicant</code>.
     */
    public static final Applicant APPLICANT = org.gdg.withgo.data.database.tables.Applicant.APPLICANT;

    /**
     * The table <code>public.event</code>.
     */
    public static final Event EVENT = org.gdg.withgo.data.database.tables.Event.EVENT;

    /**
     * The table <code>public.ticket</code>.
     */
    public static final Ticket TICKET = org.gdg.withgo.data.database.tables.Ticket.TICKET;
}
