/*
 * This file is generated by jOOQ.
 */
package org.gdg.withgo.data.database.tables.records;


import javax.annotation.Generated;

import org.gdg.withgo.data.database.tables.Applicant;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplicantRecord extends UpdatableRecordImpl<ApplicantRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1960287894;

    /**
     * Setter for <code>public.applicant.event_id</code>.
     */
    public void setEventId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.applicant.event_id</code>.
     */
    public Integer getEventId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.applicant.ticket_id</code>.
     */
    public void setTicketId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.applicant.ticket_id</code>.
     */
    public Integer getTicketId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.applicant.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.applicant.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Applicant.APPLICANT.EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Applicant.APPLICANT.TICKET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Applicant.APPLICANT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getTicketId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTicketId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicantRecord value1(Integer value) {
        setEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicantRecord value2(Integer value) {
        setTicketId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicantRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicantRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplicantRecord
     */
    public ApplicantRecord() {
        super(Applicant.APPLICANT);
    }

    /**
     * Create a detached, initialised ApplicantRecord
     */
    public ApplicantRecord(Integer eventId, Integer ticketId, Integer userId) {
        super(Applicant.APPLICANT);

        set(0, eventId);
        set(1, ticketId);
        set(2, userId);
    }
}
