/*
 * This file is generated by jOOQ.
 */
package org.gdg.withgo.data.database.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.gdg.withgo.data.database.tables.Event;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventRecord extends UpdatableRecordImpl<EventRecord> implements Record8<Integer, Integer, String, String, Date, Date, Date, Date> {

    private static final long serialVersionUID = -807040104;

    /**
     * Setter for <code>public.event.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.event.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.event.org_id</code>.
     */
    public void setOrgId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.event.org_id</code>.
     */
    public Integer getOrgId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.event.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.event.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.event.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.event.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.event.sales_start</code>.
     */
    public void setSalesStart(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.event.sales_start</code>.
     */
    public Date getSalesStart() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>public.event.sales_end</code>.
     */
    public void setSalesEnd(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.event.sales_end</code>.
     */
    public Date getSalesEnd() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>public.event.start_date</code>.
     */
    public void setStartDate(Date value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.event.start_date</code>.
     */
    public Date getStartDate() {
        return (Date) get(6);
    }

    /**
     * Setter for <code>public.event.end_date</code>.
     */
    public void setEndDate(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.event.end_date</code>.
     */
    public Date getEndDate() {
        return (Date) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, String, Date, Date, Date, Date> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, String, Date, Date, Date, Date> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Event.EVENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Event.EVENT.ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Event.EVENT.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Event.EVENT.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Event.EVENT.SALES_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return Event.EVENT.SALES_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field7() {
        return Event.EVENT.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return Event.EVENT.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component5() {
        return getSalesStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component6() {
        return getSalesEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component7() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component8() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getSalesStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getSalesEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value7() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value2(Integer value) {
        setOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value3(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value4(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value5(Date value) {
        setSalesStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value6(Date value) {
        setSalesEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value7(Date value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value8(Date value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord values(Integer value1, Integer value2, String value3, String value4, Date value5, Date value6, Date value7, Date value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventRecord
     */
    public EventRecord() {
        super(Event.EVENT);
    }

    /**
     * Create a detached, initialised EventRecord
     */
    public EventRecord(Integer id, Integer orgId, String title, String content, Date salesStart, Date salesEnd, Date startDate, Date endDate) {
        super(Event.EVENT);

        set(0, id);
        set(1, orgId);
        set(2, title);
        set(3, content);
        set(4, salesStart);
        set(5, salesEnd);
        set(6, startDate);
        set(7, endDate);
    }
}
