/*
 * This file is generated by jOOQ.
 */
package org.gdg.withgo.data.database.tables.records;


import javax.annotation.Generated;

import org.gdg.withgo.data.database.tables.OrganizationMember;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganizationMemberRecord extends UpdatableRecordImpl<OrganizationMemberRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1455830072;

    /**
     * Setter for <code>public.organization_member.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.organization_member.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.organization_member.org_id</code>.
     */
    public void setOrgId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.organization_member.org_id</code>.
     */
    public Integer getOrgId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrganizationMember.ORGANIZATION_MEMBER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return OrganizationMember.ORGANIZATION_MEMBER.ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationMemberRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationMemberRecord value2(Integer value) {
        setOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationMemberRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganizationMemberRecord
     */
    public OrganizationMemberRecord() {
        super(OrganizationMember.ORGANIZATION_MEMBER);
    }

    /**
     * Create a detached, initialised OrganizationMemberRecord
     */
    public OrganizationMemberRecord(Integer userId, Integer orgId) {
        super(OrganizationMember.ORGANIZATION_MEMBER);

        set(0, userId);
        set(1, orgId);
    }
}
